services:
  - type: web
    name: spotter-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn spotter_assessment.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0