# Generated by Django 5.2.6 on 2025-09-25 10:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Carrier company name', max_length=200)),
                ('dot_number', models.CharField(help_text='DOT number', max_length=20)),
                ('main_office_address', models.TextField(help_text='Main office address')),
                ('operates_every_day', models.BooleanField(default=True, help_text='True for 70hr/8day rule, False for 60hr/7day rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'db_table': 'carriers',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.CharField(help_text='Unique driver identifier', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Driver's full name", max_length=100)),
                ('cdl_number', models.CharField(help_text="Commercial Driver's License number", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='trips.carrier')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ELDLogSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(help_text='Date of log sheet')),
                ('sheet_number', models.IntegerField(help_text='Sheet number for multi-day trips')),
                ('total_miles', models.DecimalField(decimal_places=1, help_text='Total miles driven', max_digits=6)),
                ('vehicle_numbers', models.CharField(help_text='Vehicle identification numbers', max_length=100)),
                ('shipping_docs', models.TextField(help_text='Shipping document information')),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.driver')),
            ],
            options={
                'verbose_name': 'ELD Log Sheet',
                'verbose_name_plural': 'ELD Log Sheets',
                'db_table': 'eld_log_sheets',
                'ordering': ['log_date', 'sheet_number'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatusEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(help_text='Start time of duty status')),
                ('end_time', models.TimeField(help_text='End time of duty status')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('location', models.CharField(help_text='Location during this duty status', max_length=500)),
                ('remarks', models.TextField(help_text='Remarks for this duty period')),
                ('entry_order', models.IntegerField(help_text='Order of entry in the log')),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_entries', to='trips.eldlogsheet')),
            ],
            options={
                'verbose_name': 'Duty Status Entry',
                'verbose_name_plural': 'Duty Status Entries',
                'db_table': 'duty_status_entries',
                'ordering': ['log_sheet', 'entry_order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(help_text='Unique trip identifier', max_length=50, unique=True)),
                ('current_location', models.CharField(help_text='Starting location address', max_length=500)),
                ('pickup_location', models.CharField(help_text='Pickup location address', max_length=500)),
                ('dropoff_location', models.CharField(help_text='Delivery location address', max_length=500)),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, help_text='Hours used in current 8-day cycle (0-70)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('70.00'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('calculating', 'Calculating Route'), ('calculated', 'Route Calculated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.driver')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_order', models.IntegerField(help_text='Order of stop in sequence')),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('rest', 'Mandatory Rest Break'), ('pickup', 'Pickup Location'), ('delivery', 'Delivery Location'), ('sleeper', 'Sleeper Berth Period')], max_length=20)),
                ('location', models.CharField(help_text='Stop location address', max_length=500)),
                ('coordinates', models.JSONField(help_text='Latitude and longitude coordinates')),
                ('estimated_arrival', models.DateTimeField(help_text='Estimated arrival time')),
                ('estimated_departure', models.DateTimeField(help_text='Estimated departure time')),
                ('duration_minutes', models.IntegerField(help_text='Stop duration in minutes')),
                ('reason', models.TextField(help_text='HOS compliance reason for stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Planned Stop',
                'verbose_name_plural': 'Planned Stops',
                'db_table': 'planned_stops',
                'ordering': ['trip', 'stop_order'],
            },
        ),
        migrations.AddField(
            model_name='eldlogsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip'),
        ),
    ]
